steps:
  - label: ":whale: Build"
    command: docker/build
    agents:
      queue: "browser-test"

  - wait

  - label: ":hammer: Test"
    command: docker/test
    agents:
      queue: "browser-test"
      
  - label: ":hammer: Browser tests"
    command: docker/test-e2e
    agents:
      queue: "browser-test"      

  - wait

  - label: ":shipit: Push images"
    command: docker/push
  
  
