#!/usr/bin/env bash
set -exu
HERE=$(dirname $0)
. $HERE/common

docker build --pull \
       --build-arg GIT_ID=$GIT_SHA \
       --build-arg GIT_BRANCH=$GIT_BRANCH \
       --build-arg PKGAPI_VERSION=$PKG_VERSION \
       --tag $TAG_SHA \
       -f docker/Dockerfile \
       $PACKAGE_ROOT

docker push $TAG_SHA
