#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

docker tag $TAG_SHA $TAG_BRANCH
docker push $TAG_BRANCH

if [ $GIT_BRANCH == "master" ]; then
    docker tag $TAG_SHA $TAG_LATEST
    docker tag $TAG_SHA $TAG_VERSION
    docker push $TAG_VERSION
    docker push $TAG_LATEST
fi
