#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)

E2E_TAG=mintr-e2e

function cleardocker() {
  $HERE/clear
}

trap cleardocker EXIT

# run the mint and mintr images
. $HERE/run_app

# build the test image
docker build --tag $E2E_TAG \
  -f $HERE/test-e2e.dockerfile \
  .
  
# make sure app is available
curl --retry 10 --retry-connrefused http://localhost:8080   

# run the test image on the network
docker run --rm \
    --network=mintr_default \
    $E2E_TAG