#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA

NAME_SERVER=mintr_server

function cleanup {
    echo "Cleaning up"
    docker kill $NAME_SERVER > /dev/null || true
}

trap cleanup EXIT

docker run --rm -d \
       -p 8888:8888 \
       --name $NAME_SERVER $TAG_SHA

# Importing the data takes a while, so we'll give this a minute to come up
set +e
for attempt in $(seq 30); do
    echo "Attempt $attempt"
    RESPONSE=$(curl --silent http://localhost:8888)
    if [ "$RESPONSE" == '{"status":"success","errors":null,"data":"Welcome to mintr"}' ]; then
        echo "SUCCESS"
        exit 0
    fi
    sleep 2
done

echo "FAIL"
exit 1
